# fly.toml
app = "qdrant-fixit"

[build]
  image = "qdrant/qdrant"

[mounts]
  source = "qdrant_data"
  destination = "/qdrant/storage"

[[services]]
  internal_port = 6333
  [[services.ports]]
    port = 6333
    handlers = ["http"]
